# Configuração do Prometheus
# Sistema de Gestão de Oficina Mecânica de Motos

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'oficina-motos'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Backend API metrics
  - job_name: 'oficina-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Frontend metrics (via nginx)
  - job_name: 'oficina-frontend'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Blackbox exporter (uptime monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://oficina-motos.vercel.app
        - https://oficina-motos-backend.railway.app/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'oficina-custom-metrics'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 60s
    metrics_path: /api/metrics
    honor_labels: true

# Remote write configuration (opcional - para Grafana Cloud)
# remote_write:
#   - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
#     basic_auth:
#       username: 'your-username'
#       password: 'your-password'