// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxluyeezxvhyqtjduwbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bHV5ZWV6eHZoeXF0amR1d2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzQ1MTUsImV4cCI6MjA2MTYxMDUxNX0.6wNxLMQEle3HwNy9OgVz4loAchsM68ytggcV872PSHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);